#!/usr/bin/env bash
# mechanical-script: psk-toc.sh — generate / verify the Table of Contents block
# in portable-spec-kit.md. Closes QA-D10-01.
#
# The kit's core file has ~20 top-level sections and no in-file navigation. This
# script emits a TOC built from the REAL `## ` section headers (fence-aware — it
# skips `## ` lines that live inside ``` code/example blocks, e.g. the TASKS.md /
# RELEASES.md version-structure templates) with GitHub-compatible anchor slugs,
# and verifies the committed TOC matches so it can never silently drift.
#
# Usage:
#   bash agent/scripts/psk-toc.sh --generate [--file <md>]   # print TOC block
#   bash agent/scripts/psk-toc.sh --check    [--file <md>]   # exit 1 on drift
#
# The TOC lives between the markers below; --check compares the bytes between
# them against a fresh --generate. PSK030 (psk-sync-check.sh) calls --check.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/../.." 2>/dev/null && pwd)"
FILE="$PROJ_ROOT/portable-spec-kit.md"
MODE=""
TOC_START="<!-- TOC-START (auto-generated by agent/scripts/psk-toc.sh — do not edit by hand) -->"
TOC_END="<!-- TOC-END -->"

while [ $# -gt 0 ]; do
  case "$1" in
    --generate) MODE="generate" ;;
    --check)    MODE="check" ;;
    --file)     shift; FILE="$1" ;;
    *) echo "psk-toc: unknown arg: $1" >&2; exit 2 ;;
  esac
  shift || true
done
[ -z "$MODE" ] && { echo "psk-toc: need --generate or --check" >&2; exit 2; }
[ -f "$FILE" ] || { echo "psk-toc: file not found: $FILE" >&2; exit 2; }

# Emit the TOC block (markers + entries). Fence-aware header extraction; the
# display title is the header text up to the first " (" (keeps entries short),
# and the anchor is the GitHub slug of the FULL header text.
generate_toc() {
  printf '%s\n' "$TOC_START"
  printf '## Table of Contents\n\n'
  awk -v s="" '
    function slug(h,   t) {
      t = tolower(h)
      gsub(/[^a-z0-9 _-]/, "", t)   # drop punctuation; keep alnum/space/_/-
      gsub(/ /, "-", t)             # spaces -> hyphens (consecutive preserved)
      return t
    }
    index($0, "TOC-START") { intoc = 1 }   # skip the TOC block itself, so the
    intoc { if (index($0, "TOC-END")) intoc = 0; next }  # "## Table of Contents"
    /^```/ { f = !f; next }          # toggle code-fence state
    !f && /^## / {
      full = substr($0, 4)           # strip "## "
      sub(/[[:space:]]+$/, "", full)
      disp = full
      sub(/ \(.*$/, "", disp)        # display = up to first " ("
      printf "- [%s](#%s)\n", disp, slug(full)
    }
  ' "$FILE"
  printf '%s\n' "$TOC_END"
}

if [ "$MODE" = "generate" ]; then
  generate_toc
  exit 0
fi

# --check: extract the committed block (inclusive of markers) and diff.
if ! grep -qF "$TOC_START" "$FILE"; then
  echo "PSK030: TOC block missing from $(basename "$FILE") (run: psk-toc.sh --generate)" >&2
  exit 1
fi
committed=$(awk -v a="$TOC_START" -v b="$TOC_END" '
  index($0,a){p=1} p{print} index($0,b){p=0}
' "$FILE")
fresh=$(generate_toc)
if [ "$committed" = "$fresh" ]; then
  echo "PSK030: TOC current (sections match)"
  exit 0
else
  echo "PSK030: TOC drift — portable-spec-kit.md headers changed but TOC was not regenerated." >&2
  echo "        Fix: replace the TOC block with the output of psk-toc.sh --generate." >&2
  exit 1
fi
